# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: 2023 IPC Stochastic Planning and Reinforcement Learning Track Dry-run
short_description: The International Probabilistic Planning Competition is organized in the context of the International Conference on 
Planning and Scheduling (ICAPS). It empirically evaluates state-of-the-art planning systems on a number of benchmark problems. 
The goals of the IPC are to promote planning research, highlight challenges in the planning community and provide new and interesting problems as 
benchmarks for future research.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: IPC_2023_blue.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard
evaluation_script: evaluation_script.zip
remote_evaluation: True
is_docker_based: True
start_date: 2023-03-14 00:00:00
end_date: 2023-03-15 23:59:59
published: False

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Race Car", "Reservoir Control", "Recommender Systems", "HVAC", "UAV", "Power Generation", "Mountain Car", "Mars Rover", "Total"],
        "default_order_by": "Total",
      }

challenge_phases:
  - id: 1
    name: Day one
    description: templates/challenge_day_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2023-03-14 00:00:00
    end_date: 2023-03-14 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: day_one
    max_submissions_per_day: 1
    max_submissions_per_month: 1
    max_submissions: 1
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"
  - id: 2
    name: Day two
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2023-03-15 00:00:00
    end_date: 2023-03-15 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json
    codename: day_two
    max_submissions_per_day: 1
    max_submissions_per_month: 1
    max_submissions: 1
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
